"""Runtime-layer exports."""

from aistackd.runtime.config import CURRENT_RUNTIME_CONFIG_SCHEMA_VERSION, RuntimeConfig
from aistackd.runtime.backends import (
    LLAMA_CLI_BINARY_NAME,
    LLAMA_SERVER_BINARY_NAME,
    BackendAcquisitionAttempt,
    BackendAcquisitionError,
    BackendAcquisitionResult,
    BackendDiscoveryResult,
    LlamaCppAcquisitionPlan,
    acquire_managed_llama_cpp_installation,
    adopt_backend_installation,
    backend_installation_errors,
    discover_llama_cpp_installation,
    plan_llama_cpp_acquisition,
)
from aistackd.runtime.backend_process import (
    DEFAULT_BACKEND_STARTUP_GRACE_SECONDS,
    DEFAULT_BACKEND_STOP_TIMEOUT_SECONDS,
    BackendLaunchPlan,
    BackendProcessError,
    RunningBackendProcess,
    build_backend_launch_plan,
    launch_managed_backend_process,
    stop_managed_backend_process,
)
from aistackd.runtime.hardware import (
    CURRENT_HARDWARE_PROFILE_SCHEMA_VERSION,
    LLMFIT_BINARY_NAME,
    HardwareProfile,
    LlmfitDetectionResult,
    detect_hardware_with_llmfit,
)
from aistackd.runtime.host import (
    DEFAULT_BACKEND_BIND,
    DEFAULT_BACKEND_PORT,
    DEFAULT_HOST_API_KEY_ENV,
    DEFAULT_HOST_BIND,
    DEFAULT_HOST_PORT,
    HostServiceConfig,
    HostValidationResult,
    resolve_api_key,
    validate_host_runtime,
)
from aistackd.runtime.modes import RuntimeMode, all_runtime_modes
from aistackd.runtime.prereqs import HostInspectionReport, HostPrerequisiteCheck, inspect_host_environment
from aistackd.runtime.remote import (
    DEFAULT_REMOTE_TIMEOUT_SECONDS,
    DEFAULT_REMOTE_WRITE_TIMEOUT_SECONDS,
    ClientValidationResult,
    RemoteClientError,
    RemoteJsonResponse,
    activate_remote_model,
    fetch_remote_models,
    fetch_remote_runtime,
    install_remote_model,
    recommend_remote_models,
    resolve_remote_api_key,
    search_remote_models,
    validate_remote_runtime,
)

__all__ = [
    "CURRENT_RUNTIME_CONFIG_SCHEMA_VERSION",
    "CURRENT_HARDWARE_PROFILE_SCHEMA_VERSION",
    "DEFAULT_BACKEND_BIND",
    "DEFAULT_BACKEND_PORT",
    "DEFAULT_BACKEND_STARTUP_GRACE_SECONDS",
    "DEFAULT_BACKEND_STOP_TIMEOUT_SECONDS",
    "DEFAULT_HOST_API_KEY_ENV",
    "DEFAULT_HOST_BIND",
    "DEFAULT_HOST_PORT",
    "DEFAULT_REMOTE_TIMEOUT_SECONDS",
    "DEFAULT_REMOTE_WRITE_TIMEOUT_SECONDS",
    "BackendLaunchPlan",
    "BackendAcquisitionAttempt",
    "BackendAcquisitionError",
    "BackendAcquisitionResult",
    "BackendDiscoveryResult",
    "BackendProcessError",
    "HostServiceConfig",
    "HardwareProfile",
    "HostInspectionReport",
    "HostPrerequisiteCheck",
    "HostValidationResult",
    "ClientValidationResult",
    "LLMFIT_BINARY_NAME",
    "LLAMA_CLI_BINARY_NAME",
    "LLAMA_SERVER_BINARY_NAME",
    "LlamaCppAcquisitionPlan",
    "LlmfitDetectionResult",
    "RemoteClientError",
    "RemoteJsonResponse",
    "RunningBackendProcess",
    "RuntimeConfig",
    "RuntimeMode",
    "acquire_managed_llama_cpp_installation",
    "activate_remote_model",
    "adopt_backend_installation",
    "all_runtime_modes",
    "backend_installation_errors",
    "build_backend_launch_plan",
    "detect_hardware_with_llmfit",
    "discover_llama_cpp_installation",
    "fetch_remote_models",
    "fetch_remote_runtime",
    "inspect_host_environment",
    "install_remote_model",
    "launch_managed_backend_process",
    "plan_llama_cpp_acquisition",
    "recommend_remote_models",
    "resolve_api_key",
    "resolve_remote_api_key",
    "search_remote_models",
    "stop_managed_backend_process",
    "validate_remote_runtime",
    "validate_host_runtime",
]
